### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by ZZZMiya** [bigboNed3/chinese_text_cnn#4]
求大神帮忙解答一下，我用您的程序在我电脑上运行，总是会报这个错
Traceback (most recent call last):
  File "E:/software/code/sentimentanalysis/chinese_text_cnn/main.py", line 70, in <module>
    train_iter, dev_iter = load_dataset(text_field, label_field, args, device=-1, repeat=False, shuffle=True)
  File "E:/software/code/sentimentanalysis/chinese_text_cnn/main.py", line 52, in load_dataset
    train_dataset, dev_dataset = dataset.get_dataset('data', text_field, label_field)
  File "E:\software\code\sentimentanalysis\chinese_text_cnn\dataset.py", line 23, in get_dataset
    ('text', text_field)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torchtext\data\dataset.py", line 78, in splits
    os.path.join(path, train), **kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torchtext\data\dataset.py", line 269, in __init__
    next(reader)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torchtext\utils.py", line 130, in unicode_csv_reader
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long
我的电脑系统是win10，python版本是python3.6

**Comment by izhx** [comment]
把torchtext库的utils.py文件的第130行注释掉就行了，这个库的代码问题
![image](https://user-images.githubusercontent.com/26690193/65050076-6806a380-d999-11e9-93c0-0f2ac82e0cf2.png)

前面在try里已经调用了，并且那个除以10就是为了避免这个错误，出来之后，又错误的调用一次，不知道维护的人咋搞的。
我这样修复了，暂时没发现不正常的地方。

**Comment by izhx** [comment]
或者把这一行的sys.maxsize换成maxInt

**Comment by ZZZMiya** [comment]
好的，我试试看哈。谢谢您能回复我，好人一生平安👍


 
---Original---
